#!/bin/bash

echo "Select the compilation option:"
echo "1) Compile with -fast and debug options"
echo "2) Compile for GPU with standard parallelism"
read -p "Enter your choice (1 or 2): " choice

case $choice in
    1)
        echo "Compiling with -fast and debug options..."

        # Compile all module files first (-c) in proper dependency order
        nvfortran -c -fast -g -Mbounds -Mchkstk -traceback -Minform=inform -module ./f90 -I./f90 \
            f90/module_save_data_files.f90 \
            f90/module_allocatable_arrays.f90 \
            f90/module_shared_variables.f90 \
	    f90/module_defect_function.f90 \
            f90/module_finite_difference_constants.f90 \
            f90/module_initial_conditions.f90 \
            f90/module_solve_TDGL.f90 \
            f90/module_test_convergence.f90 \
            f90/module_save_output.f90 \
            f90/create_data_file.f90 \
            f90/create_directories.f90 \
            f90/write_to_file.f90 \
            f90/move_files.f90

        # Link all object files with main
        nvfortran -fast -g -Mbounds -Mchkstk -traceback -Minform=inform -module ./f90 -I./f90 \
            -o test *.o f90/main.f90
        ;;
    2)
        echo "Compiling for GPU with standard parallelism..."

        nvfortran -c -stdpar=gpu -Minfo=accel -module ./f90 -I./f90 \
            f90/module_save_data_files.f90 \
            f90/module_allocatable_arrays.f90 \
            f90/module_shared_variables.f90 \
	    f90/module_defect_function.f90 \
            f90/module_finite_difference_constants.f90 \
            f90/module_initial_conditions.f90 \
            f90/module_solve_TDGL.f90 \
            f90/module_test_convergence.f90 \
            f90/module_save_output.f90 \
            f90/create_data_file.f90 \
            f90/create_directories.f90 \
            f90/write_to_file.f90 \
            f90/move_files.f90

        nvfortran -stdpar=gpu -Minfo=accel -module ./f90 -I./f90 \
            -o test *.o f90/main.f90
        ;;
    *)
        echo "Invalid choice. Exiting."
        exit 1
        ;;
esac

# Check if the compilation was successful
if [ $? -eq 0 ]; then
    echo "Compilation successful. Executable 'test' created."
else
    echo "Compilation failed."
fi

rm -f *.o
